// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/storefront/DarkPro.tsx": () => import("../components/mockups/storefront/DarkPro.tsx"),
  "./components/mockups/storefront/WarmCommerce.tsx": () => import("../components/mockups/storefront/WarmCommerce.tsx")
};
